os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "6.11.0"
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - node
    - node_modules
    - $HOME/.m2
    - $HOME/.yarn-cache
env:
  global:
    - NODE_VERSION=6.11.0
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  # Repo for Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - npm install -g firebase-tools
install:
  - yarn install
after_success:
  # Send coverage data to Codecov
  - bash <(curl -s https://codecov.io/bash)
  # Start e2e test via sauce (on hold for now)
  # - npm run e2e protractor.sauce.conf.js
  # Deploy to firebase
  - npm run fireDeployPrep
  - firebase deploy --token=${FIREBASE_API_TOKEN}
script:
  - chmod +x mvnw
  - ./mvnw clean test
  - yarn test
  # - ./mvnw com.heroku.sdk:heroku-maven-plugin:1.1.1:deploy -DskipTests -Pprod -Dheroku.appName=great-big-example-application
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
